[build]
  publish = "public"
  command = "npm install"

[dev]
  framework = "#custom"
  command = "python app.py"
  targetPort = 5000

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
